import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { Box } from "@mui/material";

import theme from "@/theme";
import ReduxProvider from "@/libs/redux/redux-provider";
import ReactQueryProvider from "@/libs/tanstack/react-query-provider";
import Header from "@/components/common/header";
import LeftSidebar from "@/components/common/left-sidebar";
import RightSidebar from "@/components/common/right-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <ReduxProvider>
              <ReactQueryProvider>
                <Box
                  sx={{
                    display: "flex",
                    bgcolor: "#f0f2f5",
                    minHeight: "100vh",
                  }}
                >
                  <Header />
                  <LeftSidebar />
                  <Box
                    component="main"
                    sx={{
                      flexGrow: 1,
                      p: 3,
                      width: { sm: `calc(100% - 480px)` },
                      mt: 8,
                    }}
                  >
                    {children}
                  </Box>
                  <RightSidebar />
                </Box>
              </ReactQueryProvider>
            </ReduxProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
